version: '3'
services:
    broker:
        build: broker
        environment:
            URLS: http://auldfellas:8081/,http://girlpower:8082/,http://dodgydrivers:8083/
        ports:
          - "8080:8080"
    auldfellas:
        build: auldfellas 
        expose:
        - 8081
    girlpower:
        build: girlpower 
        expose:
        - 8082
    dodgydrivers:
        build: dodgydrivers
        expose:
        - 8083